connection_url = "udp://:14551"
local_server = "http://127.0.0.1:5006"
upload_service = 0
remote_server = "https://review.px4.io"
credentials_file = ""
email = ""
upload_enabled = false
public_logs = false
